from __future__ import annotations

from aden_tools.credentials.base import CredentialSpec

SIMILARWEB_CREDENTIALS = {
    "similarweb": CredentialSpec(
        env_var="SIMILARWEB_API_KEY",
        tools=[
            "similarweb_get_website_overview",
            "similarweb_get_pages_per_visit",
            "similarweb_get_average_visit_duration",
            "similarweb_get_bounce_rate",
            "similarweb_get_page_views",
            "similarweb_get_desktop_vs_mobile",
            "similarweb_get_deduplicated_audience",
            "similarweb_get_global_rank",
            "similarweb_get_country_rank",
            "similarweb_get_industry_rank",
            "similarweb_get_geography",
            "similarweb_get_similar_competitors",
            "similarweb_get_traffic_sources",
            "similarweb_get_top_keywords",
            "similarweb_get_audience_geography",
            "similarweb_get_app_overview",
            "similarweb_get_audience_interests",
            "similarweb_get_top_outgoing_links",
            "similarweb_get_category_leaders",
            "similarweb_get_technologies",
            "similarweb_get_social_media_traffic",
            "similarweb_get_referring_websites",
            "similarweb_get_subdomain_traffic",
            "similarweb_get_top_pages",
            "similarweb_get_app_ranking",
            "similarweb_get_app_engagement",
            "similarweb_get_display_ads_publishers",
            "similarweb_get_paid_search_competitors",
            "similarweb_get_ad_creatives",
            "similarweb_get_cross_browsing_behavior",
            "similarweb_get_company_info",
            "similarweb_get_desktop_visits",
            "similarweb_get_desktop_pages_per_visit",
            "similarweb_get_desktop_average_visit_duration",
            "similarweb_get_desktop_bounce_rate",
            "similarweb_get_desktop_pageviews",
            "similarweb_get_keyword_analysis",
            "similarweb_get_keyword_competitors",
            "similarweb_get_app_dau_mau",
            "similarweb_get_app_retention",
            "similarweb_get_app_session_details",
            "similarweb_get_conversion_rate",
            "similarweb_get_desktop_unique_visitors",
            "similarweb_get_desktop_geography",
            "similarweb_get_desktop_visits_by_channel",
            "similarweb_get_desktop_pages_per_visit_by_channel",
            "similarweb_get_desktop_average_visit_duration_by_channel",
            "similarweb_get_desktop_bounce_rate_by_channel",
            "similarweb_get_desktop_referrals",
            "similarweb_get_desktop_social_referrals",
            "similarweb_get_desktop_ad_networks",
            "similarweb_get_desktop_display_publishers",
            "similarweb_get_desktop_publishers_per_ad_network",
            "similarweb_get_desktop_organic_keyword_competitors",
            "similarweb_get_desktop_paid_keyword_competitors",
            "similarweb_get_desktop_organic_outgoing_links",
            "similarweb_get_desktop_outgoing_ads_networks",
            "similarweb_get_desktop_outgoing_ads_advertisers",
            "similarweb_get_desktop_traffic_sources_by_channel",
            "similarweb_get_desktop_ppc_spend",
            "similarweb_get_mobile_traffic_sources_by_channel",
            "similarweb_get_mobile_referrals",
            "similarweb_get_mobile_outgoing_referrals",
            "similarweb_get_mobile_organic_keyword_competitors",
            "similarweb_get_mobile_paid_keyword_competitors",
            "similarweb_get_all_traffic_ppc_spend",
            "similarweb_get_audience_demographics_groups",
            "similarweb_get_audience_demographics_age",
            "similarweb_get_audience_demographics_gender",
            "similarweb_get_audience_interests_all",
            "similarweb_get_audience_interests_desktop",
            "similarweb_get_audience_interests_mobile",
            "similarweb_get_audience_overlap_desktop",
            "similarweb_get_audience_new_vs_returning",
            "similarweb_get_subdomains_desktop",
            "similarweb_get_subdomains_mobile",
            "similarweb_get_folders",
            "similarweb_get_popular_pages",
            "similarweb_get_custom_segments",
            "similarweb_get_predefined_segments",
            "similarweb_get_segment_traffic_total",
            "similarweb_get_segment_traffic_desktop",
            "similarweb_get_segment_marketing_channels_desktop",
            "similarweb_get_segment_marketing_channels_all",
            "similarweb_get_conversion_segments",
            "similarweb_get_conversion_analysis_desktop",
            "similarweb_get_api_lite",
            "similarweb_get_website_description",
            "similarweb_get_top_similar_rank",
            "similarweb_get_top_sites_total",
            "similarweb_get_top_sites_desktop",
            "similarweb_get_top_sites_mobile",
            "similarweb_get_rank_tracking_campaigns",
            "similarweb_get_rank_tracking_position_trend",
            "similarweb_get_rank_tracking_snapshot",
            "similarweb_get_rank_tracker_describe",
            "similarweb_get_list_companies",
            "similarweb_get_company_analysis_total",
            "similarweb_get_company_analysis_desktop",
            "similarweb_get_company_analysis_mobile",
            "similarweb_get_website_technologies",
            "similarweb_get_batch_describe_tables",
            "similarweb_get_test_webhooks",
            "similarweb_get_remaining_credits",
            "similarweb_get_remaining_user_credits",
        ],
        required=True,
        help_url="https://developer.similarweb.com/",
        description="API key for SimilarWeb traffic and competitor insights.",
        direct_api_key_supported=True,
        api_key_instructions="""To get a SimilarWeb API key:
1. Go to the SimilarWeb Developer Portal (https://developer.similarweb.com/)
2. Or log into your SimilarWeb Pro account at pro.similarweb.com
3. Navigate to Account Settings > API (or Data Extraction / API section)
4. Click on "Generate API Key"
5. Copy the generated API key and securely store it in your .env file""",
        credential_id="similarweb",
        credential_key="api_key",
        health_check_endpoint="https://api.similarweb.com/v1/website/google.com/total-traffic-and-engagement/visits",
    )
}
